[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "hydraflow"
version = "0.2.18"
description = "Hydraflow integrates Hydra and MLflow to manage and track machine learning experiments."
readme = "README.md"
license = "MIT"
authors = [{ name = "daizutabi", email = "daizutabi@gmail.com" }]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
]
requires-python = ">=3.10"
dependencies = [
  "hydra-core>=1.3",
  "joblib",
  "mlflow>=2.15",
  "rich",
  "watchdog",
  "watchfiles",
]

[project.urls]
Documentation = "https://github.com/daizutabi/hydraflow"
Source = "https://github.com/daizutabi/hydraflow"
Issues = "https://github.com/daizutabi/hydraflow/issues"

[tool.uv]
dev-dependencies = [
  "pytest-asyncio",
  "pytest-clarity",
  "pytest-cov",
  "pytest-randomly",
  "pytest-xdist",
  "ruff",
]

[tool.hatch.build.targets.sdist]
exclude = ["/.github", "/docs"]

[tool.hatch.build.targets.wheel]
packages = ["src/hydraflow"]

[tool.pytest.ini_options]
addopts = [
  "--doctest-modules",
  "--cov=hydraflow",
  "--cov-report=lcov:lcov.info",
]
doctest_optionflags = ["NORMALIZE_WHITESPACE", "IGNORE_EXCEPTION_DETAIL"]
filterwarnings = ['ignore:pkg_resources is deprecated:DeprecationWarning']
asyncio_default_fixture_loop_scope = "function"

[tool.coverage.report]
exclude_lines = ["no cov", "raise NotImplementedError", "if TYPE_CHECKING:"]

[tool.ruff]
line-length = 88
target-version = "py310"

[tool.ruff.lint]
select = ["ALL"]
unfixable = ["F401"]
ignore = [
  "ANN003",
  "ANN401",
  "ARG002",
  "B904",
  "D105",
  "D107",
  "D203",
  "D213",
  "EM101",
  "PGH003",
  "TRY003",
]
exclude = ["tests/scripts/*.py", "src/hydraflow/__init__.py"]

[tool.ruff.lint.per-file-ignores]
"tests/*" = [
  "A001",
  "ANN",
  "ARG",
  "D",
  "FBT",
  "PLR",
  "PT",
  "S",
  "SIM117",
  "SLF",
]
