[tool.poetry]
name = "glider-ingest"
version = "1.1.13"
description = "Package for GERG to ingest raw glider data into NetCDF files"
authors = ["Alec <alecmkrueger@tamu.edu>"]
readme = "README.md"
packages = [{include = "glider_ingest", from = "src"}]


[tool.poetry.dependencies]
python = "^3.12"
numpy = "^2.0.1"
pandas = "^2.2.2"
xarray = "^2024.6.0"
attrs = "^23.2.0"
gsw = "^3.6.19"
scipy = "^1.14.0"
netcdf4 = "^1.7.1.post1"
natsort = "^8.4.0"
dask = "^2024.8.2"
dask-expr = "^1.1.13"
dbdreader = "^0.5.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


