[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "commonlisteners"
version = "0.0.6"
authors = [
  { name="Andrey Smirnov", email="smirnovcode@mail.ru" },
]
description = "Let you subscribe and listen in right manner"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: CC0 1.0 Universal (CC0 1.0) Public Domain Dedication",
    "Operating System :: OS Independent",
]

[project.urls]
"Github repo" = "https://github.com/akvilary/commonlisteners"
"Bug tracker" = "https://github.com/akvilary/commonlisteners/issues"
"Release notes in Telegram" = "https://t.me/commonlisteners"
