[project]
name = "SMS_BP"

version = "0.1.65"

description = "Single Molecule Simulations and Microscopy Simulations developed for the Weber Lab by Baljyot Singh Parmar"

readme = "README.md"

requires-python = "==3.10.13"

license = { file = "license.md" }

keywords = ["SMS"]

authors = [
  { name = "Baljyot Singh Parmar", email = "baljyotparmar@hotmail.com" },
]

maintainers = [
  { name = "Baljyot Singh Parmar", email = "baljyotparmar@hotmail.com" },
]

dependencies = [
  "numpy>=1.21.2",
  "matplotlib>=3.6.0",
  "scipy>=1.7.1",
  "scikit-image>=0.18.3",
  "mkdocs==1.6.0",
]

[tool.pyright]
venvPath = "."
venv = ".venv"

[tool.uv]
dev-dependencies = ["mkdocs==1.6.0", "pymdown-extensions>=10.11"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
run_SMS_BP = "SMS_BP.run_cell_simulation:main_CLI"
SMS_BP_config = "SMS_BP.run_cell_simulation:create_config"
