[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "simo"
version = "2.2.11"
authors = [
  { name="Simanas VenÄkauskas", email="simanas@simo.io" },
]
description = "Smart Home on Steroids!"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dynamic = ["dependencies"]
[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[project.scripts]
simo-install = "simo.management.install:install"

[project.urls]
Homepage = "https://simo.io"
Issues = "https://github.com/pypa/sampleproject/issues"

