[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "PyTubeStudio"
version = "0.0.3"
authors = [
  { name="Jaarfi"},
]
description = "A library to interact with the VTubeStudio API"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
    "pydantic>=2.7",
    "websockets>=12.0",
    "platformdirs",
    "aiofiles"
]