[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "fastflight"
authors = [{ name = "Chao Ning", email = "chao.ning.uk@gmail.com" }]
description = "FastAPI and Arrow Flight integrated server offering efficient dual-protocol support for both REST and gRPC data streaming."
version = "0.2.2"
readme = "README.md"
requires-python = ">= 3.10"
dependencies = [
    "asyncpg",
    "fastapi>=0.110.2",
    "pandas",
    "pyarrow>=14.0.0",
    "pydantic>=2.0",
    "sqlalchemy[asyncio]",
]

[project.optional-dependencies]
dev = ["pre-commit"]
test = ["pytest", "pytest-cov"]

[tool.ruff]
line-length = 120
src = ["src", "tests", "demo"]

[tool.ruff.format]
skip-magic-trailing-comma = true

[tool.ruff.lint]
# On top of the default `select` (`E4`, E7`, `E9`, and `F`), enable isort (`I`)
extend-select = ["I"]