# pyproject.toml

[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "episode_segmenter"
version = "1.0.20"
description = "Annotates activitiy episodes represented by meshes moving in a 3D environment with the corresponding events, actions and activities."
readme = "README.md"
authors = [{ name = "Abdelrhman Bassiouny", email = "abassiou@uni-bremen.de" }]
license = { file = "LICENSE" }
classifiers = [
    "Programming Language :: Python :: 3",
]
keywords = ["robotics", "knowledge", "memories", "episodic", "pycram"]
dependencies = ["neem_pycram_interface==1.0.167",
]
requires-python = ">=3.8"

[project.urls]
Homepage = "https://github.com/AbdelrhmanBassiouny/EpisodeSegmenter"
