[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "lanscape"
version = "0.5.3"
authors = [
  { name="Michael Dennis", email="michael@dipduo.com" },
]
description = "A python based local network scanner"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "Flask==3.0.3",
    "psutil==6.0.0",
    "pywebview>=4.2",
    "scapy>=2.3.2",
]
[project.urls]
Homepage = "https://github.com/mdennis281/py-lanscape"
Issues = "https://github.com/mdennis281/py-lanscape/issues"
