[tool.poetry]
name = "donnedessouscharles"
version = "0.1.0"
description = ""
authors = ["carlosmagni"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
opencv-python = "^4.10.0.84"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
