[tool.poetry]
name = "guc-cms-scrapper"
version = "0.2.0"
description = "A package to scrap the GUC university CMS to get the courses and their details"
authors = ["Mathew Hany <mathew.hanybb@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.32.3"
beautifulsoup4 = "^4.12.3"
requests-ntlm = "^1.3.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
