[tool.poetry]
name = "FedCL"
version = "0.1.1"
description = ""
authors = ["Maciej Krzysztof Zuziak <maciej.k.zuziak@protonmail.com>"]
readme = "README.md"
packages = [{include = "FedCL"}]

[tool.poetry.dependencies]
python = "^3.10"
torch = ">= 2.2.0"
torchvision = ">= 0.1.5"
datasets = ">= 2.17.0"
numpy = "1.26.4"
scikit-learn = ">= 1.4"
timm = ">= 1.0.8"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
