[project]
name = "abs-sleep"
authors = [
  { name="BjÃ¶rn Brandenburg", email="bbb@mpi-sws.org" },
]
version = "0.1.0"
description = "Thin ctypes wrapper for calling Linux's `clock_nanosleep` with `TIMER_ABSTIME`"
readme = "README.md"
requires-python = ">=3.7"
dependencies = []
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: POSIX :: Linux",
]


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
